MyTodo/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path("", include('todoapp.urls')),
    path('', include('contact.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

contact/urls.py
from django.urls import path
from .views import ContactView

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact'),
]

todoapp/urls.py
from django.urls import path
from  .views import Todos, delete_all, delete_completed, delete_todo, mark_completed, mark_uncompleted

app_name = "todoapp"

urlpatterns = [
    path("", Todos.as_view(), name='home'),
    path("delete_all/", delete_all, name="delete_all"),
    path("delete_completed/", delete_completed, name="delete_completed"),
    path("delete/<int:todo_id>/", delete_todo, name="delete"),
    path("mark_completed/<int:todo_id>/", mark_completed, name="completed"),
    path("mark_uncompleted/<int:todo_id>/", mark_uncompleted, name="uncompleted"),
    #path("<int:pk>/delete/", DeleteView.as_view(), name='delete_todo')
]

contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(blank=True, max_length=200)
    email = models.EmailField(max_length=150)
    message = models.TextField()

    objects = models.Manager

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.email

todoapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Todo(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    completed = models.BooleanField(default=False)
    date_created = models.DateField(auto_now_add=True)

    objects = models.Manager

    def __str__(self):
        return self.title

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

        widgets = {'name':forms.TextInput(attrs={'placeholder':'Optional'})}
        

todoapp/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['title']
        labels = {"title":""}
        widgets = {"title":forms.TextInput(attrs={"placeholder":"What do you plan to do today?"})}

contact/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.contrib import messages
from .models import Contact
from django.template.loader import get_template
from .forms import ContactForm
from django.views.generic import View


class ContactView(View):
    login_url = 'account_login'

    def get(self, request, *args, **kwargs):
        form = ContactForm()
        context = {"form":form}
        return render(request, 'contact.html', context)

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            email = request.POST['email']
            message = request.POST['message']

            subject = 'Contact Form Received'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [settings.DEFAULT_FROM_EMAIL]

            context = {
                'user': name,
                'email': email,
                'message': message
            }

            contact_message = get_template('contact_message.txt').render(context)

            send_mail(subject, contact_message, from_email, to_email, fail_silently=True)
            form.save()
            messages.info(request, 'Your message has been received.')
        return redirect("todoapp:home")

todoapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.http import JsonResponse
# from django.core import serializers
from django.urls import reverse, reverse_lazy
from django.views.generic import View, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import TodoForm
from.models import Todo


class Todos(LoginRequiredMixin, View):
    login_url = "account_login"
    redirect_field_name = 'next'

    def get(self, *args, **kwargs):
        form = TodoForm()
        todo_list = Todo.objects.filter(owner__username=self.request.user.username).order_by("-id")
        context = {"form":form, "todo_list":todo_list}
        return render(self.request, "todo_list.html", context)

    def post(self, *args, **kwargs):
        form = TodoForm(self.request.POST or None)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.owner = self.request.user
            todo.save()
            messages.success(self.request, 'Todo added successfully.')
            return redirect("todoapp:home")
        return render(self.request, "todo_list.html", {"form": form})
        

def delete_all( request):
    todos = Todo.objects.filter(owner__username=request.user.username)
    if request.method == 'POST':
        todos.delete()
        messages.success(request, 'You have successfully deleted all your todo.')
        return redirect("todoapp:home")
    return render(request, "delete_all.html") 

def delete_completed(request):
    todos = Todo.objects.filter(owner__username=request.user.username).filter(completed__exact=True)
    if request.method == 'POST':
        todos.delete()
        messages.success(request, 'You have successfully deleted all the completed todo.')
        return redirect("todoapp:home")
    context = {'todos':todos}
    return render(request, "delete_completed.html", context)

def delete_todo(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        todo.delete()
        messages.success(request, 'Todo successfully deleted.')
        return redirect("todoapp:home")
    context = {'todo': todo}
    return render(request, "delete.html", context)


def mark_completed(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        todo.completed = True
        todo.save()
        messages.info(request, 'successfully marked completed!')
        return redirect("todoapp:home")
    context = {'todo':todo}
    return render(request, 'mark_completed.html', context)

def mark_uncompleted(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        todo.completed = False
        todo.save()
        messages.info(request, 'successfully marked uncompleted!')
        return redirect("todoapp:home")
    context = {'todo':todo}
    return render(request, 'mark_uncompleted.html', context)

templates/base.html
{% load static %}
{% load account %}
{% load sri %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TodoApp{% endblock %}</title>
    {% sri_static "css/base.css" %}
    <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body style="background-color: black;">
    {% include 'messages.html' %}
    <header class="sticky-top bg-white">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand mb-1" href="JavaScript:void(0)">TodoApp</a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
                        <li class="nav-item navig">
                            <a  class="nav-link text-dark" href="{% url 'todoapp:home' %}">Home</a>
                        </li>
                        <li class="nav-item navig">
                            <a class="nav-link text-dark" href="{% url 'contact:contact' %}">Get in touch</a>
                        </li>
                    </ul>
                    <div>
                        {% if request.user.is_authenticated %}
                        <div class="dropdown">
                        <a class="dropdown-toggle btn btn-secondary mt-2 mt-lg-0" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"> {{ request.user }}</i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                        </div>
                        </div>
                        {% else %}
                        <div>
                            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                                <li class="nav-item ">
                                    <a class="nav-link btn btn-outline-info m-2" href="{% url 'account_login' %}"><i class="fa fa-sign-in" aria-hidden="true"> Sign in</i></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link btn btn-secondary m-2" href="{% url 'account_signup' %}"><i class="fa fa-user-plus" aria-hidden="true"> Sign up</i></a>
                                </li>
                            </ul>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <section>
        <img style="width: 100%;" class="img-fluid" src="{% static 'images/original.jpg' %}" alt="original">
    </section>
    {% block content %}
    <div class="container my-5">

    </div>
    {% endblock %}
    <div class="my-4 text-center">
        <a style="color: #f4cbb2;" class="btn bg-white mr-2" href="https://github.com/Jokotoye18" target="_blank"><i class="fa fa-github" aria-hidden="true"> Github</i></a>
        <a style="color: #008abe;" class="btn bg-white mr-2" href="https://twitter.com/AkinJokotoye" target="_blank"><i class="fa fa-twitter-square" aria-hidden="true"> Twitter</i></a>
        <a style="color: #B23121;" class="btn bg-white mr-2" href="{% url 'contact:contact' %}"><i class="fa fa-envelope" aria-hidden="true"> Contact</i></a>
    </div>
    <div class="text-center rounded text-white">
        <div class="my-4">
            <p>© 2020 | Developed By Ademola_oba</p>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}contact{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-outline-dark" type="submit" value="contact">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}delete todo{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="mb-5">
                        <p class="lead">Are you sure you want to delete <span class="lead ml-3 text-danger ">'{{ todo.title }}'</span> ?</p>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger">comfirm</button>
                        <a class="btn btn-info" href="{% url 'todoapp:home' %}">cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/delete_all.html
{% extends 'base.html' %}
{% load static %}

{% block title %}delete_all{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <p>Are you sure you want to delete all your todo?</p>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger">comfirm</button>
                        <a class="btn btn-info" href="{% url 'todoapp:home' %}">cancel</a>
                    </form>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/delete_completed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}delete_completed{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% if not todos %}
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <p>You did not have any completed todo. Go back to <a class="btn btn-outline-info ml-2" href="{% url 'todoapp:home' %}">home</a></p>
                    </div>
                </div> 
            </div>
            {% else %}
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <p>Are you sure you want to delete all the completed todo?</p>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger">comfirm</button>
                        <a class="btn btn-info" href="{% url 'todoapp:home' %}">cancel</a>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/mark_completed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}mark_completed{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <p>Are you sure you want to mark <span class="text-warning mx-3">{{ todo}}</span>completed?</p>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-warning">comfirm</button>
                        <a class="btn btn-info" href="{% url 'todoapp:home' %}">cancel</a>
                    </form>
                </div>
            </div>
        </div> 
    </div>
</div>
{% endblock %}

templates/mark_uncompleted.html
{% extends 'base.html' %}
{% load static %}

{% block title %}mark_uncompleted{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <p>Are you sure you want to mark <span class="text-warning mx-3">{{ todo}}</span>uncompleted?</p>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-warning">comfirm</button>
                        <a class="btn btn-info" href="{% url 'todoapp:home' %}">cancel</a>
                    </form>
                </div>
            </div>
        </div> 
    </div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" style="margin: 0;">
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <i class="fa fa-close"></i>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/todo_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block content %}
<div class="container my-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-8">
            <div class="card border border-dark">
                <div class="card-header">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-block btn-info lead" ><i class="fa fa-plus" ></i> Add</button>
                    </form>
                    <div class=" d-flex my-3 justify-content-center text-center align-items-center">
                        {% if todo_list %}
                            <a class="btn btn-danger mx-2 lead" href="{% url 'todoapp:delete_all' %}">Delete all</a>
                            <a class="btn btn-danger mx-2 lead" href="{% url 'todoapp:delete_completed' %}">Delete completed</a>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer">
                    {% for todo in todo_list %}
                        <div class="row justify-content-between my-3 ">
                            <div class="col-10 align-items-center">
                                {% if todo.completed %}
                                <div class=" bg-success text-white rounded d-flex">
                                    <div>
                                        <p class="px-1" style="display: inline-block; text-decoration: line-through;"><a class="text-white"  href="{% url 'todoapp:uncompleted' todo.id %}">{{ todo.title }}</a></p>
                                    </div>                                    
                                </div>
                                {% else %}
                                <div class=" bg-secondary text-white rounded d-flex">
                                    <div>
                                        <p class="px-1" style="display: inline-block;"><a class="text-white" href="{% url 'todoapp:completed' todo.id %}">{{ todo.title }}</a></p>
                                    </div>                                    
                                </div>
                                {% endif %}
                            </div>
                            <div class="col-2 align-self-center text-left">
                                <a href="{% url 'todoapp:delete' todo.id %}"><i class="fa fa-trash-o  text-danger"></i></a>
                            </div>
                        </div> 
                    {% empty %}
                        <p class="lead">You have not added any todo yet. </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>                    
{% endblock %}